"""
Generated protobuf messages for RAG service.
This file is a placeholder - generate actual code using:
  python -m grpc_tools.protoc -I../rag-service/protos --python_out=. --grpc_python_out=. rag/v1/rag_service.proto
"""
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rag/v1/rag_service.proto
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_sym_db = _symbol_database.Default()

# Enum values
INGEST_STAGE_UNSPECIFIED = 0
INGEST_STAGE_DOWNLOADING = 1
INGEST_STAGE_PARSING = 2
INGEST_STAGE_CHUNKING = 3
INGEST_STAGE_EMBEDDING = 4
INGEST_STAGE_STORING = 5
INGEST_STAGE_COMPLETE = 6
INGEST_STAGE_ERROR = 7

RELEVANCE_UNSPECIFIED = 0
RELEVANCE_HIGH = 1
RELEVANCE_MEDIUM = 2
RELEVANCE_LOW = 3

SERVICE_STATUS_UNSPECIFIED = 0
SERVICE_STATUS_SERVING = 1
SERVICE_STATUS_NOT_SERVING = 2


class BBox:
    """Bounding box message."""
    def __init__(self, x0=0.0, y0=0.0, x1=0.0, y1=0.0):
        self.x0 = x0
        self.y0 = y0
        self.x1 = x1
        self.y1 = y1


class IngestPdfRequest:
    """Ingest PDF request message."""
    def __init__(self, document_url="", document_id="", chunk_size=750):
        self.document_url = document_url
        self.document_id = document_id
        self.chunk_size = chunk_size


class IngestResult:
    """Ingest result message."""
    def __init__(self, success=False, document_id="", status="", chunks_count=0, created_at="", error=""):
        self.success = success
        self.document_id = document_id
        self.status = status
        self.chunks_count = chunks_count
        self.created_at = created_at
        self.error = error


class IngestPdfProgress:
    """Ingest progress message."""
    def __init__(self, stage=0, progress_percent=0, message="", result=None):
        self.stage = stage
        self.progress_percent = progress_percent
        self.message = message
        self.result = result or IngestResult()


class QueryRequest:
    """Query request message."""
    def __init__(self, query="", document_id="", document_name="", top_k=20, min_score=0.04):
        self.query = query
        self.document_id = document_id
        self.document_name = document_name
        self.top_k = top_k
        self.min_score = min_score


class RagSource:
    """RAG source message."""
    def __init__(self, name="", page=0, section="", exact_text="", bboxes=None, relevance=RELEVANCE_HIGH):
        self.name = name
        self.page = page
        self.section = section
        self.exact_text = exact_text
        self.bboxes = bboxes or []
        self.relevance = relevance


class RagAnswer:
    """RAG answer message."""
    def __init__(self, response="", sources=None):
        self.response = response
        self.sources = sources or []


class QueryTiming:
    """Query timing message."""
    def __init__(self, embedding_ms=0.0, retrieval_ms=0.0, generation_ms=0.0, total_ms=0.0, chunks_retrieved=0, chunks_compressed=0):
        self.embedding_ms = embedding_ms
        self.retrieval_ms = retrieval_ms
        self.generation_ms = generation_ms
        self.total_ms = total_ms
        self.chunks_retrieved = chunks_retrieved
        self.chunks_compressed = chunks_compressed


class CacheInfo:
    """Cache info message."""
    def __init__(self, embedding_cache_hit=False, semantic_cache_hit=False, chunk_cache_hit=False, response_cache_hit=False, semantic_similarity=0.0):
        self.embedding_cache_hit = embedding_cache_hit
        self.semantic_cache_hit = semantic_cache_hit
        self.chunk_cache_hit = chunk_cache_hit
        self.response_cache_hit = response_cache_hit
        self.semantic_similarity = semantic_similarity


class QueryResponse:
    """Query response message."""
    def __init__(self, answer=None, timing=None, cache_info=None):
        self.answer = answer or RagAnswer()
        self.timing = timing or QueryTiming()
        self.cache_info = cache_info or CacheInfo()


class GetHighlightedPdfRequest:
    """Highlighted PDF request message."""
    def __init__(self, document_url="", page=0, bboxes=None):
        self.document_url = document_url
        self.page = page
        self.bboxes = bboxes or []


class HighlightedPdfResponse:
    """Highlighted PDF response message."""
    def __init__(self, pdf_content=b"", content_type="application/pdf"):
        self.pdf_content = pdf_content
        self.content_type = content_type


class InvalidateDocumentRequest:
    """Invalidate document request message."""
    def __init__(self, document_id=""):
        self.document_id = document_id


class InvalidateDocumentResponse:
    """Invalidate document response message."""
    def __init__(self, success=False, chunks_deleted=0, cache_entries_deleted=0):
        self.success = success
        self.chunks_deleted = chunks_deleted
        self.cache_entries_deleted = cache_entries_deleted


class HealthCheckRequest:
    """Health check request message."""
    pass


class ComponentHealth:
    """Component health message."""
    def __init__(self, name="", healthy=False, message=""):
        self.name = name
        self.healthy = healthy
        self.message = message


class HealthCheckResponse:
    """Health check response message."""
    def __init__(self, status=SERVICE_STATUS_UNSPECIFIED, version="", components=None):
        self.status = status
        self.version = version
        self.components = components or []
